### ISSUE TITLE
Geheime Daten auslagern und git ignore hinzufügen

### ISSUE THREAD

**Issue by thomasgatterer** [toqix/RFID-Relay#2]
ssid und pwt und auch ip des json rechners sollten in einer weiteren Datei hinterlegt sein, und dann eingelesen werden. So kann man sie mit einem git ignore bequem vergessen beim pushen.

**Comment by toqix** [comment]
Werde ich beim nächsten commit so machen, aber trotzdem eine Beispieldatei erstellen.
